version: '3.3'

services:
  db:
    image: postgres:11.1-alpine
    ports:
      - 5437:5432
    environment:
      POSTGRES_DB: reddit-clone
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres