version: '3.3'

services:
  db:
    image: postgres:12.4-alpine
    ports:
      - 5437:5432
    environment:
      POSTGRES_DB: reddit-clone
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
